# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

from google.colab import drive
drive.mount('/content/drive')

!ls /content/drive/MyDrive
!ls "/content/drive/MyDrive/New_folder"

from pathlib import Path

BASE = Path("/content/drive/MyDrive/New_folder/badodd")

image_exts = [".jpg", ".jpeg", ".png"]

all_images = [p for p in BASE.rglob("*") if p.is_file() and p.suffix.lower() in image_exts]

print("Total images found:", len(all_images))

from pathlib import Path

BADODD = Path("/content/drive/MyDrive/New_folder/badodd")
image_exts = [".jpg", ".jpeg", ".png"]

all_images = [p for p in BADODD.rglob("*") if p.is_file() and p.suffix.lower() in image_exts]
all_labels = [p for p in BADODD.rglob("*.txt")]

print("Total images:", len(all_images))
print("Total labels:", len(all_labels))

print("\nSample image names:")
for p in all_images[:5]:
    print(p.name, "-> stem:", p.stem)

print("\nSample label names:")
for p in all_labels[:5]:
    print(p.name, "-> stem:", p.stem)

from pathlib import Path
from collections import Counter, defaultdict
import os

BASE = Path("/content/drive/MyDrive/New_folder/badodd")
IMAGE_EXTS = {".jpg", ".jpeg", ".png"}

all_images = [p for p in BASE.rglob("*") if p.is_file() and p.suffix.lower() in IMAGE_EXTS]
all_labels = [p for p in BASE.rglob("*.txt")]

label_map = {p.stem: p for p in all_labels}

matched_images = []
missing_labels = []

for img in all_images:
    if img.stem in label_map:
        matched_images.append(img)
    else:
        missing_labels.append(img)

print("Total images:", len(all_images))
print("Total labels:", len(all_labels))
print("Matched image-label pairs:", len(matched_images))
print("Images without labels:", len(missing_labels))

!rm -rf /content/badodd
!cp -r "/content/drive/MyDrive/New_folder/badodd" /content/
!ls /content/badodd | head

import shutil
from pathlib import Path

BADODD = Path("/content/badodd")
OUT = Path("/content/badodd_clean_11")

shutil.rmtree(OUT, ignore_errors=True)
(OUT / "images").mkdir(parents=True, exist_ok=True)
(OUT / "labels").mkdir(parents=True, exist_ok=True)

image_exts = [".jpg", ".jpeg", ".png"]

badodd_to_11 = {
    0: 1,   # Auto_ricksaw
    1: 2,   # Bike
    2: 3,   # Bus
    6: 2,   # Bike
    11: 9   # Truck
}

images = [p for p in BADODD.rglob("*") if p.is_file() and p.suffix.lower() in image_exts]
labels = {p.stem: p for p in BADODD.rglob("*.txt")}

saved = 0

for img in images:
    lbl = labels.get(img.stem)
    if not lbl:
        continue

    new_lines = []

    with open(lbl, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            parts = line.strip().split()
            if len(parts) == 5:
                cls = int(float(parts[0]))
                if cls in badodd_to_11:
                    parts[0] = str(badodd_to_11[cls])
                    new_lines.append(" ".join(parts))

    if new_lines:
        new_name = f"bad_{saved:06d}"
        shutil.copy2(img, OUT / "images" / f"{new_name}{img.suffix.lower()}")
        with open(OUT / "labels" / f"{new_name}.txt", "w") as f:
            f.write("\n".join(new_lines) + "\n")
        saved += 1

        if saved % 500 == 0:
            print("Processed:", saved)

print("FINAL saved:", saved)

!ls /content/badodd_clean_11/images | wc -l
!ls /content/badodd_clean_11/labels | wc -l

!rm -rf "/content/drive/MyDrive/New_folder/badodd_clean_11"
!cp -r /content/badodd_clean_11 "/content/drive/MyDrive/New_folder/"

import shutil
from pathlib import Path

ORIG_IMG = Path("/content/drive/MyDrive/New_folder/images2")
ORIG_LBL = Path("/content/drive/MyDrive/New_folder/labels2")

BAD_IMG = Path("/content/drive/MyDrive/New_folder/badodd_clean_11/images")
BAD_LBL = Path("/content/drive/MyDrive/New_folder/badodd_clean_11/labels")

COMBINED = Path("/content/drive/MyDrive/New_folder/final_11class_combined")
shutil.rmtree(COMBINED, ignore_errors=True)

(COMBINED / "images").mkdir(parents=True, exist_ok=True)
(COMBINED / "labels").mkdir(parents=True, exist_ok=True)

image_exts = [".jpg", ".jpeg", ".png"]

count_orig = 0
for img in ORIG_IMG.rglob("*"):
    if img.is_file() and img.suffix.lower() in image_exts:
        lbl = ORIG_LBL / f"{img.stem}.txt"
        if lbl.exists():
            new_stem = f"orig_{count_orig:05d}"
            shutil.copy2(img, COMBINED / "images" / f"{new_stem}{img.suffix.lower()}")
            shutil.copy2(lbl, COMBINED / "labels" / f"{new_stem}.txt")
            count_orig += 1

count_bad = 0
for img in BAD_IMG.rglob("*"):
    if img.is_file() and img.suffix.lower() in image_exts:
        lbl = BAD_LBL / f"{img.stem}.txt"
        if lbl.exists():
            new_stem = f"bad_{count_bad:05d}"
            shutil.copy2(img, COMBINED / "images" / f"{new_stem}{img.suffix.lower()}")
            shutil.copy2(lbl, COMBINED / "labels" / f"{new_stem}.txt")
            count_bad += 1

print("Original copied:", count_orig)
print("Badodd copied:", count_bad)
print("Total combined images:", len(list((COMBINED / "images").glob("*"))))
print("Total combined labels:", len(list((COMBINED / "labels").glob("*.txt"))))

import random
import shutil
from pathlib import Path

BASE = Path("/content/drive/MyDrive/New_folder/final_11class_combined")
SPLIT = Path("/content/final_11class_split")

shutil.rmtree(SPLIT, ignore_errors=True)

(SPLIT / "train/images").mkdir(parents=True, exist_ok=True)
(SPLIT / "train/labels").mkdir(parents=True, exist_ok=True)
(SPLIT / "valid/images").mkdir(parents=True, exist_ok=True)
(SPLIT / "valid/labels").mkdir(parents=True, exist_ok=True)
(SPLIT / "test/images").mkdir(parents=True, exist_ok=True)
(SPLIT / "test/labels").mkdir(parents=True, exist_ok=True)

images = [p for p in (BASE / "images").iterdir() if p.suffix.lower() in [".jpg", ".jpeg", ".png"]]

random.seed(42)
random.shuffle(images)

n = len(images)
train_end = int(0.8 * n)
valid_end = int(0.9 * n)

train_imgs = images[:train_end]
valid_imgs = images[train_end:valid_end]
test_imgs = images[valid_end:]

def copy_pair(img_list, img_dest, lbl_dest):
    for img in img_list:
        lbl = BASE / "labels" / f"{img.stem}.txt"
        if lbl.exists():
            shutil.copy2(img, img_dest / img.name)
            shutil.copy2(lbl, lbl_dest / lbl.name)

copy_pair(train_imgs, SPLIT / "train/images", SPLIT / "train/labels")
copy_pair(valid_imgs, SPLIT / "valid/images", SPLIT / "valid/labels")
copy_pair(test_imgs, SPLIT / "test/images", SPLIT / "test/labels")

print("Train:", len(list((SPLIT / 'train/images').glob('*'))))
print("Valid:", len(list((SPLIT / 'valid/images').glob('*'))))
print("Test:", len(list((SPLIT / 'test/images').glob('*'))))

yaml_text = """
train: /content/final_11class_split/train/images
val: /content/final_11class_split/valid/images
test: /content/final_11class_split/test/images

nc: 11
names: ['Ambulance', 'Auto_ricksaw', 'Bike', 'Bus', 'Fire_truck', 'Leguna', 'Pickup', 'Police_car', 'Private_car', 'Truck', 'cng']
"""

with open("/content/final_11class_split/data.yaml", "w") as f:
    f.write(yaml_text)

print("Final data.yaml created.")
print(yaml_text)

!pip install -q ultralytics

from ultralytics import YOLO

model = YOLO("yolov8s.pt")

model.train(
    data="/content/final_11class_split/data.yaml",
    epochs=20,
    imgsz=640,
    batch=16,
    project="/content/drive/MyDrive/New_folder/final_runs",
    name="traffic_final",
    exist_ok=True
)

from google.colab import files
files.download("/content/drive/MyDrive/New_folder/final_runs/traffic_final/weights/best.pt")

#trial1
from google.colab import files
files.upload()

results = model.predict("/content/gettyimages-1501064033-640_adpp.mp4", save=True)

!ls runs/detect

!ls runs/detect/predict
!ls runs/detect/predict2
!ls runs/detect/predict3

import os

base = "runs/detect"

for folder in os.listdir(base):
    path = os.path.join(base, folder)
    if os.path.isdir(path):
        print(f"\n📁 {folder}:")
        print(os.listdir(path))

import os

base = "runs/detect"

for folder in os.listdir(base):
    path = os.path.join(base, folder)
    if os.path.isdir(path):
        print(f"\n📁 {folder}:")
        print(os.listdir(path))

from google.colab import files
files.download("runs/detect/predict/gettyimages-1501064033-640_adpp.avi")

#trial2
from google.colab import files
files.upload()

results = model.predict("/content/Recording 2026-04-06 012320.mp4", save=True)

import os

base = "runs/detect"

for folder in os.listdir(base):
    path = os.path.join(base, folder)
    if os.path.isdir(path):
        print(f"\n📁 {folder}:")
        print(os.listdir(path))

from google.colab import files
files.download("runs/detect/predict/Recording 2026-04-06 012320.avi")

#trial3
from google.colab import files
files.upload()

results = model.predict("/content/Recording 2.mp4", save=True)

results = model.predict("/content/Recording 3.mp4", save=True)

results = model.predict("/content/Recording 4.mp4", save=True)

import os

base = "runs/detect"

for folder in os.listdir(base):
    path = os.path.join(base, folder)
    if os.path.isdir(path):
        print(f"\n📁 {folder}:")
        print(os.listdir(path))

from google.colab import files
files.download("runs/detect/predict/Recording 2.avi")

from google.colab import files
files.download("runs/detect/predict/Recording 3.avi")

from google.colab import files
files.download("runs/detect/predict/Recording 4.avi")